swagger: '2.0'
info:
  version: "1.0.0"
  title: Тестовый код
  description: Пример API для статей
host: forester.ru
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
